# import streamlit as st
# from sentiment_analysis_model import load_and_preprocess_data, train_lstm_model
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# import os
# import pickle
#
# # Load and train the LSTM model
# file_path = "stock_sentiment/stock_senti_analysis.csv"
# X, y = load_and_preprocess_data(file_path)
#
# # Check if the model and tokenizer already exist
# if os.path.exists("lstm_sentiment_model.h5") and os.path.exists("tokenizer.pkl"):
#     from tensorflow.keras.models import load_model
#     model = load_model("lstm_sentiment_model.h5")
#     with open("tokenizer.pkl", "rb") as handle:
#         tokenizer = pickle.load(handle)
#     accuracy = None  # Accuracy won't be recalculated if loading pre-trained model
# else:
#     model, tokenizer, accuracy = train_lstm_model(X, y)
#     model.save("lstm_sentiment_model.h5")
#     with open("tokenizer.pkl", "wb") as handle:
#         pickle.dump(tokenizer, handle)
#
# # Streamlit app
# st.title("Stock Sentiment Analysis")
# if accuracy:
#     st.write(f"Model Accuracy: {accuracy:.2f}")
#
# # Input form
# user_input = st.text_area("Enter news headline(s):", height=150)
#
# if st.button("Predict Sentiment"):
#     if user_input.strip():
#         # Preprocess the input
#         input_sequence = tokenizer.texts_to_sequences([user_input])
#         input_padded = pad_sequences(input_sequence, maxlen=200)
#
#         # Predict sentiment
#         prediction = model.predict(input_padded)
#         sentiment = "Positive sentiment" if prediction[0][0] > 0.5 else "Negative sentiment"
#         st.write(f"Predicted Sentiment: **{sentiment}**")
#     else:
#         st.write("Please enter some text to analyze.")

import os
import pickle
import streamlit as st
from sentiment_analysis_model import load_and_preprocess_data, preprocess_features, train_mlp_model, predict_sentiment_percentage

# Load and preprocess data
file_path = "stock_sentiment/stock_senti_analysis.csv"
X, y = load_and_preprocess_data(file_path)
X_processed, vectorizer, scaler = preprocess_features(X)

# Check if the required files exist
required_files = ["mlp_sentiment_model.pkl", "vectorizer.pkl", "scaler.pkl"]
missing_files = [file for file in required_files if not os.path.exists(file)]

if missing_files:
    st.error(f"Missing required files: {', '.join(missing_files)}. Please ensure the files are generated by running the training script.")
else:
    # Load the pre-trained model, vectorizer, and scaler
    with open("mlp_sentiment_model.pkl", "rb") as model_file:
        model = pickle.load(model_file)
    with open("vectorizer.pkl", "rb") as vectorizer_file:
        vectorizer = pickle.load(vectorizer_file)
    with open("scaler.pkl", "rb") as scaler_file:
        scaler = pickle.load(scaler_file)

    # Train the model and get accuracy
    model, accuracy = train_mlp_model(X_processed, y)

    # Streamlit app
    st.title("Stock Sentiment Analysis with MLP")
    st.write(f"Model Accuracy: {accuracy * 100:.2f}%")

    # Input form
    user_input = st.text_area("Enter news headline(s):", height=150)

    if st.button("Predict Sentiment"):
        if user_input.strip():
            # Predict sentiment percentages
            positive, negative = predict_sentiment_percentage(model, vectorizer, scaler, user_input)
            st.write(f"**Positive Sentiment:** {positive:.2f}%")
            st.write(f"**Negative Sentiment:** {negative:.2f}%")
            sentiment = "Positive" if positive > negative else "Negative"
            st.subheader(f"Overall Sentiment: **{sentiment}**")
        else:
            st.warning("Please enter some text to analyze.")

# Logistic reg: UI code
# import streamlit as st
# from sentiment_analysis_model import load_and_preprocess_data, preprocess_features, train_logistic_regression_model, predict_sentiment_percentage
# import os
# import pickle
#
# # Load and preprocess data
# file_path = "stock_sentiment/stock_senti_analysis.csv"
# X, y = load_and_preprocess_data(file_path)
# X_processed, vectorizer = preprocess_features(X)
#
# # Check if the model already exists
# if os.path.exists("logistic_regression_model.pkl"):
#     with open("logistic_regression_model.pkl", "rb") as model_file:
#         model = pickle.load(model_file)
#     accuracy = None  # Accuracy won't be recalculated if loading pre-trained model
# else:
#     model, accuracy = train_logistic_regression_model(X_processed, y)
#     with open("logistic_regression_model.pkl", "wb") as model_file:
#         pickle.dump(model, model_file)
#
# # Streamlit app
# st.title("Stock Sentiment Analysis with Logistic Regression")
# if accuracy:
#     st.write(f"Model Accuracy: {accuracy * 100:.2f}%")
#
# # Input form
# user_input = st.text_area("Enter news headline(s):", height=150)
#
# if st.button("Predict Sentiment"):
#     if user_input.strip():
#         # Predict sentiment percentages
#         positive, negative = predict_sentiment_percentage(model, vectorizer, user_input)
#         st.write(f"Positive Sentiment: **{positive:.2f}%**")
#         st.write(f"Negative Sentiment: **{negative:.2f}%**")
#         sentiment = "Positive" if positive > negative else "Negative"
#         st.write(f"Overall Sentiment: **{sentiment}**")
#     else:
#         st.write("Please enter some text to analyze.")